### PR TITLE
flash different images depending on the usb-chip on the badge.

### PR DESCRIPTION
**Pull request by basvs**
**PARTIALLY** **tested**

### CODE REVIEW

**Comment by basvs** [comment]
$ grep CP2102 /sys/dev/char/189\:*/product

/sys/dev/char/189:7/product:CP2102N USB to UART Bridge Controller
/sys/dev/char/189:8/product:CP2102N USB to UART Bridge Controller
/sys/dev/char/189:9/product:CP2102 USB to UART Bridge Controller

**Comment by basvs** [comment]
Apparently, we cannot use the 'product' string to see the difference after all.

But we can still use some code from this branch..

**Comment by annejan** [comment]
Will try and help figure it out tomorrow.

**Comment by basvs** [comment]
We found a difference in the USB implementation! :)

Will update this code this afternoon / tonight and add a type 'F'.

**Comment by basvs** [comment]
**UPDATED**

Now recognises 3 types:
- CP2102 (real)
- CP2102 (fake)
- CP2102N

The png image is now split in 3 images; to display correctly, it still needs some changes in the Firmware repository.

To see the correct image: (After booting into micropython)

    badge.eink_png(0,0, '/media/hacking.png')
    badge.eink_png(2,2, '/media/badge_version.png')
    badge.eink_png(0,0, '/media/badge_type.png')
    ugfx.flush(0xf0)

**Review by annejan — APPROVED** [review]

**Pull request merged**
